[package]
name = "_01_bit_counting"
version = "0.1.0"
authors = ["Ersan Egorov <egorov.ea@students.dvfu.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
